#!/bin/sh
# filesize.sh — repo-wide source-file line-count ratchet gate.
#
# Mirrors `make deadcode`: it snapshots every tracked .go/.ts/.tsx file whose
# line count exceeds LIMIT into filesize.baseline.
#
#   check  (default) — fail when a file newly crosses LIMIT, when a baselined
#                      file grows past its recorded count, or when a baselined
#                      file has dropped to <= LIMIT (its stale line must go).
#   update           — re-snapshot filesize.baseline (accept the current tree).
#
# Toolset is intentionally portable POSIX (git/wc/sort/grep/join/sed) so it
# runs identically on macOS (BSD) and Linux (GNU). LC_ALL=C keeps sort/join
# byte-deterministic across both.

set -eu
export LC_ALL=C

LIMIT=300
ROOT=$(git rev-parse --show-toplevel)
BASELINE=$ROOT/filesize.baseline
TAB=$(printf '\t')
cd "$ROOT"

# snapshot: emit "path<TAB>count" for every tracked source file over LIMIT,
# sorted by path. Shared by both modes so the two paths produce identical counts.
snapshot() {
	git ls-files "*.go" "*.ts" "*.tsx" | while IFS= read -r f; do
		[ -f "$f" ] || continue # deleted paths remain in the index until commit
		n=$(wc -l < "$f" | tr -d ' ')   # strip BSD wc's leading spaces
		if [ "$n" -gt "$LIMIT" ]; then
			printf '%s\t%s\n' "$f" "$n"
		fi
	done | sort
}

write_baseline() {
	{
		cat <<EOF
# filesize.baseline — tracked source files over $LIMIT lines, accepted by \`make filesize\`.
#
# \`make filesize\` lists every tracked .go/.ts/.tsx file whose line count exceeds
# $LIMIT (the CLAUDE.md source-file limit). The entries below are the files that
# already exceeded that limit when the ratchet was introduced; they are
# grandfathered in so the gate can block *new* growth without forcing a
# repo-wide split first.
#
# The gate is a ratchet: a baselined file may only shrink. \`make filesize\` fails when
#   * a file not listed here crosses $LIMIT lines (split it, or accept via make filesize-update);
#   * a listed file grows beyond its recorded count (regrowth);
#   * a listed file drops to <= $LIMIT lines or is deleted/renamed — its line below
#     is now stale, so delete the line (or run make filesize-update).
#
# Generated by scripts/filesize.sh; never hand-edit. Regenerate with \`make filesize-update\`.
# Format: "<path><TAB><line count>", sorted by path.
#
EOF
		snapshot
	} > "$BASELINE"
	# `|| true`: grep -c exits 1 when zero lines match (an empty baseline once
	# every oversized file is split), which set -e would otherwise treat as fatal.
	count=$(grep -v '^#' "$BASELINE" | grep -c . || true)
	echo "filesize: baseline updated ($count files over $LIMIT lines)"
}

check() {
	now=$(mktemp)
	base=$(mktemp)
	trap 'rm -f "$now" "$base"' EXIT INT TERM
	snapshot > "$now"
	grep -v '^#' "$BASELINE" | grep . | sort > "$base"

	# Outer-join current vs baseline on path -> "path<TAB>cur<TAB>base"; either
	# count may be empty. Parameter expansion (not `read`) splits the row so
	# empty fields survive — IFS=<tab> would collapse them.
	offenders=$(
		join -t "$TAB" -a1 -a2 -e '' -o '0,1.2,2.2' "$now" "$base" |
		while IFS= read -r line; do
			path=${line%%"$TAB"*}
			rest=${line#*"$TAB"}
			cur=${rest%%"$TAB"*}
			bse=${rest#*"$TAB"}
			if [ -z "$bse" ]; then
				printf '%s:%s vs limit %s  NEW (not in baseline)\n' "$path" "$cur" "$LIMIT"
			elif [ -z "$cur" ]; then
				printf '%s:%s  STALE (now <= %s; remove this baseline line)\n' "$path" "$bse" "$LIMIT"
			elif [ "$cur" -gt "$bse" ]; then
				printf '%s:%s vs baseline %s  REGROWTH\n' "$path" "$cur" "$bse"
			fi
		done
	)

	if [ -n "$offenders" ]; then
		echo "filesize: files violating the $LIMIT-line ratchet:"
		echo "$offenders" | sed 's/^/  /'
		echo "Split the file under $LIMIT lines, or (for an accepted change) run 'make filesize-update'."
		exit 1
	fi
	echo "filesize: no new files over $LIMIT lines"
}

mode=${1:-check}
case "$mode" in
	check)  check ;;
	update) write_baseline ;;
	*) echo "usage: $0 [check|update]" >&2; exit 2 ;;
esac
